version: '3.8'


services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5432"
    networks:
      - go-network
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_PASSWORD=gorm
      - POSTGRES_USER=gorm
      - POSTGRES_DB=gorm
      - TZ=Asia/Shanghai


networks:
  go-network:
    driver: bridge

volumes:
  pgdata:
    driver: local